<!-- BEGIN JS -->
<script src="{{ asset('admin-assets/assets/plugins/jquery/dist/jquery-3.6.1.min.js') }}"></script>
<script src="{{ asset('admin-assets/assets/plugins/bootstrap/bootstrap5/js/bootstrap.bundle.min.js') }}"></script>
<script src="{{ asset('admin-assets/assets/plugins/metisMenu/dist/metisMenu.min.js') }}"></script>
<script src="{{ asset('admin-assets/assets/plugins/paper-ripple/dist/PaperRipple.min.js') }}"></script>
<script src="{{ asset('admin-assets/assets/plugins/malihu-custom-scrollbar-plugin/jquery.mCustomScrollbar.concat.min.js') }}"></script>
<script src="{{ asset('admin-assets/assets/plugins/sweetalert2/dist/sweetalert2.min.js') }}"></script>
<script src="{{ asset('admin-assets/assets/plugins/screenfull/dist/screenfull.min.js') }}"></script>
<script src="{{ asset('admin-assets/assets/plugins/iCheck/icheck.min.js') }}"></script>
<script src="{{ asset('admin-assets/assets/plugins/switchery/dist/switchery.js') }}"></script>
<script src="{{ asset('admin-assets/assets/js/core.js') }}"></script>
<!-- END JS -->